# Generated by Django 5.0.7 on 2024-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='availability',
            field=models.CharField(default='Available', max_length=10),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('WHITE', 'White'), ('BLACK', 'Black'), ('GREY', 'Grey')], default='RED', max_length=10),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='previousPrice',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra L'), ('XXL', 'Double Xl')], default='S', max_length=10),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sku',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='qty',
            field=models.IntegerField(default=None),
        ),
    ]
